version: "2"

services:
    mysql:
        container_name: helpnamiki_mysql
        hostname:   helpnamiki_mysql
        image:  mariadb
        volumes:
            - ./DB/mysql:/var/lib/mysql
            - ./DB/init:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: helpnamiki
